services:
  - type: web
    name: 7ch-render
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
