const http=require('http');
const fs=require('fs');
const path=require('path');
const {URL}=require('url');
const PORT=Number(process.env.PORT||10000);
const GAS_URL='https://script.google.com/macros/s/AKfycby-dEiWyuKtqTuNpRu4uZxDQsH7mGIQT_K9II1kVH_tNUkp2sPB_0hKN-HoBVKLbZuYvw/exec';
const FRONTEND=fs.readFileSync(path.join(__dirname,'frontend.html'),'utf8');
function headers(type){return {'Content-Type':type,'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0','Pragma':'no-cache','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; connect-src 'self'; frame-src 'none'; child-src 'none'; object-src 'none'; base-uri 'self'; frame-ancestors 'none';"};}
function send(res,status,type,body){res.writeHead(status,headers(type));res.end(body);}
function clientIp(req){const f=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();const r=String(req.headers['x-real-ip']||'').trim();const s=String(req.socket&&req.socket.remoteAddress||'').trim();return(f||r||s).replace(/^::ffff:/i,'');}
async function gas(action,method,body,ip){const u=new URL(GAS_URL);u.searchParams.set('renderApi','1');u.searchParams.set('action',action);const res=await fetch(u,{method,redirect:'follow',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json; charset=utf-8'},body:method==='POST'?JSON.stringify(Object.assign({},body,{clientIp:body&&body.clientIp||ip})):undefined});const text=await res.text();let data;try{data=JSON.parse(text);}catch(e){throw new Error('GASからJSONを取得できませんでした。HTTP '+res.status+' / '+text.slice(0,240));}if(!res.ok||!data||data.success===false)throw new Error(data&&data.message?data.message:'GAS APIエラー');return data.data;}
function escJson(v){return JSON.stringify(v==null?'':v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');}
async function page(req){const u=new URL(req.url,'http://localhost');const cfg=await gas('render_config','GET',{},clientIp(req));let out=FRONTEND;out=out.replaceAll('"__INITIAL_THREAD_ID__"',escJson(u.searchParams.get('thread')||''));out=out.replaceAll('"__ANONYMOUS_NAME__"',escJson(cfg&&cfg.anonymousName||'名無しさん'));out=out.replaceAll('"__ADMIN_SESSION__"','""');out=out.replaceAll('"__ADMIN_SIGNUP_URL__"',escJson(cfg&&cfg.adminSignupUrl||''));out=out.replaceAll('"__TOTAL_ACCESS__"',String(Number(cfg&&cfg.totalAccess||0)));out=out.replaceAll('"__RULE_TEXT__"',escJson(cfg&&cfg.ruleText||''));out=out.replaceAll('"__INFO_VOTE_DATA__"',escJson(cfg&&cfg.infoVoteData||{question:'',options:[]}));out=out.replaceAll('__SERVICE_NOTICE_HTML__',String(cfg&&cfg.serviceNoticeHtml||''));return out;}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/healthz')return send(res,200,'application/json; charset=utf-8',JSON.stringify({ok:true,service:'7ch-render-r-exact'}));if(u.pathname==='/rpc'){let raw='';for await(const c of req)raw+=c;let b={};try{b=raw?JSON.parse(raw):{};}catch(e){return send(res,400,'application/json; charset=utf-8',JSON.stringify({ok:false,message:'RPC JSONが不正です。'}));}const data=await gas('rpc','POST',{method:String(b.method||''),args:Array.isArray(b.args)?b.args:[]},clientIp(req));return send(res,200,'application/json; charset=utf-8',JSON.stringify({ok:true,data}));}if(u.pathname==='/'||u.pathname==='/index.html'){return send(res,200,'text/html; charset=utf-8',await page(req));}return send(res,404,'text/plain; charset=utf-8','Not Found');}catch(e){return send(res,500,'text/plain; charset=utf-8',String(e&&e.message?e.message:e));}});
server.listen(PORT,'0.0.0.0',()=>console.log('7ch Render R exact listening on '+PORT));
